version: '3'

volumes:
    logs:
        driver: local

services:
    nginx:
        image: nginx
        volumes:
            - ./www:/var/www
            - ./nginx/logs:/etc/nginx/logs/
            - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 10101:80
            - 10201:443

        depends_on:
            - brt-app

    brt-app:
        build: .
        environment:
            docker: "true"
            DB_HOST: "mariadb"
            DB_USER: "[user]"
            DB_NAME: "brt"
            DB_PASS: "[db's password]"
            MAIL_HOST: "[smtp server name]"
            MAIL_USERBASE: "[smtp user name base (@example.com)]"
            MAIL_PASSWORD: "[smtp password]"
            MAIL_SECURE: "[smtp secure type]"
            MAIL_PORT: "[smtp port no]"
            MAIL_ADDRESSBASE: "[from address base (@example.com)]"
        volumes:
            - logs:/var/www/logs
            - ./www:/var/www
        working_dir: /var/www
        depends_on:
            - mariadb
        command: "composer install"

    mariadb:
        image: mariadb:10.5
        volumes:
            - ./mariadb:/var/lib/mysql
        ports:
            - "10301:3306"
        environment:
            MYSQL_ROOT_PASSWORD: [password]
