SET GLOBAL sql_mode="STRICT_TRANS_TABLES";

CREATE DATABASE IF NOT EXISTS brt;
USE brt;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name CHAR(32) NOT NULL UNIQUE,
    mail CHAR(64) NOT NULL UNIQUE,
    password_hash CHAR(255) NOT NULL,
    url_param CHAR(255) NOT NULL,
    last_updated_at BIGINT UNSIGNED NOT NULL,
    last_logdin_at BIGINT UNSIGNED NOT NULL,
    flag INT UNSIGNED DEFAULT 0 NOT NULL)
    ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bento (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name CHAR(64) NOT NULL,
    discription TEXT NOT NULL,
    deadline_at BIGINT NOT NULL,
    sale_at BIGINT NOT NULL,
    flag INT UNSIGNED DEFAULT 0 NOT NULL)
    ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS confirm_mails (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    mail TEXT NOT NULL UNIQUE,
    session_id CHAR(255) NOT NULL UNIQUE,
    set_at BIGINT UNSIGNED NOT NULL,
    flag INT UNSIGNED DEFAULT 0 NOT NULL)
    ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    bento_id BIGINT UNSIGNED NOT NULL,
    ordered_at BIGINT NOT NULL,
    users_id BIGINT UNSIGNED NOT NULL,
    flag INT UNSIGNED NOT NULL DEFAULT 0,
    FOREIGN KEY (users_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (bento_id) REFERENCES bento (id) ON DELETE CASCADE)
    ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
