SET GLOBAL sql_mode="STRICT_TRANS_TABLES";

CREATE DATABASE IF NOT EXISTS brt;
USE brt;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    student_no INT UNSIGNED,
    first_name CHAR(32) NOT NULL,
    last_name CHAR(32) NOT NULL,
    mail TEXT NOT NULL UNIQUE,
    password_hash CHAR(255) NOT NULL,
    url_param CHAR(255) NOT NULL,
    last_updated_at BIGINT UNSIGNED NOT NULL,
    last_logdin_at BIGINT UNSIGNED NOT NULL,
    type INT UNSIGNED NOT NULL,
    flag INT UNSIGNED DEFAULT 0 NOT NULL)
    ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bento (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name CHAR(64) NOT NULL,
    discription TEXT NOT NULL,
    price INT UNSIGNED NOT NULL,
    order_deadline_at BIGINT UNSIGNED NOT NULL,
    start_sale_at BIGINT UNSIGNED NOT NULL,
    end_sale_at BIGINT UNSIGNED NOT NULL,
    stock INT UNSIGNED DEFAULT NULL,
    flag INT UNSIGNED DEFAULT 0 NOT NULL)
    ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS confirm_mails (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    mail TEXT NOT NULL UNIQUE,
    target CHAR(255) NOT NULL,
    session_id CHAR(255) NOT NULL UNIQUE,
    set_at BIGINT UNSIGNED NOT NULL,
    flag INT UNSIGNED DEFAULT 0 NOT NULL)
    ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    bento_id BIGINT UNSIGNED NOT NULL,
    quantity INT UNSIGNED NOT NULL,
    ordered_at BIGINT NOT NULL,
    users_id BIGINT UNSIGNED NOT NULL,
    flag INT UNSIGNED NOT NULL DEFAULT 0,
    FOREIGN KEY (users_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (bento_id) REFERENCES bento (id) ON DELETE CASCADE)
    ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS informations (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title CHAR(255) NOT NULL,
    text TEXT DEFAULT NULL,
    set_at BIGINT NOT NULL,
    flag INT UNSIGNED NOT NULL DEFAULT 0)
    ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

