<?php

// ユーザータイプ
const USER_TYPE_ADMIN = 2;
const USER_TYPE_GENERAL = 1;

// DBフラグ
const BENTO_ORDER_CLOSED = 1;

# 日本語の曜日
const DAY_JP = ["日", "月", "火", "水", "木", "金", "土"];

// メニュー追加のデフォルト値
const DEFAULT_START_SALE_HOUR = 11;
const DEFAULT_START_SALE_MINUTE = 30;
const DEFAULT_SALE_LENGTH_HOUR = 1;
const DEFAULT_SALE_LENGTH_MINUTE = 0;
const DEFAULT_ORDER_DEADLINE_DATE_BEFORE = 0;
const DEFAULT_ORDER_DEADLINE_HOUR = 8;
const DEFAULT_ORDER_DEADLINE_MINUTE = 30;

const ORDER_TAKE_LIMIT_BEFORE_MINUTE = 15;
